# -*- coding: utf-8 -*-
"""diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/2002bhawna/2e084e97930b1e12007cf8cfb976e8b4/diabetes.ipynb
"""

# step 1: import library
import pandas as pd

# step 2: import data
diabetes = pd.read_csv("https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Diabetes.csv")

diabetes.head()

diabetes.describe()

diabetes.info()

diabetes.columns

y=diabetes["diabetes"]

x= diabetes[['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age']]

# step4: split
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7,stratify=y,random_state=2529)

x_train.shape,x_test.shape,y_train.shape,y_test.shape

x_train

# step5: select a model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)

# step6: train model
model.fit(x_train,y_train)

# step7: predict
y_pred=model.predict(x_test)

# step8: accuracy
from sklearn.metrics import accuracy_score , classification_report

accuracy_score(y_test,y_pred)

print(classification_report(y_test,y_pred))